/**
 * \file
 * \brief CPU 1D Convolution function declarations
 */
#ifndef CPU_CONVOLUTION_1D_H
#define CPU_CONVOLUTION_1D_H

/**
 * \brief ...
 * \param in ...
 * \param out ...
 * \param rSigmaEff ...
 * \param rad ...
 * \param inWidth ...
 * \param outWidth ...
 * \param outHeight ...
 * \param inOutOffset ...
 * \return void
 */
void xConvCpu(const float* const in, float* const out, const float rSigmaEff, const unsigned int rad, const int inWidth, const int outWidth, const int outHeight, const int inOutOffset);

/**
 * \brief ...
 * \param in ...
 * \param out ...
 * \param rSigmaEff ...
 * \param rad ...
 * \param inWidth ...
 * \param outWidth ...
 * \param outHeight ...
 * \param inOutOffset ...
 * \return void
 */
void xConvCpuScat(const float* const in, float* const out, const float rSigmaEff, const unsigned int rad, const unsigned int inWidth, const unsigned int outWidth, const unsigned int outHeight, const unsigned int inOutOffset);

/**
 * \brief ...
 * \param in ...
 * \param out ...
 * \param rSigmaEff ...
 * \param rad ...
 * \param inWidth ...
 * \param outWidth ...
 * \param outHeight ...
 * \param inOutOffset ...
 * \param inOutDelta ...
 * \return void
 */
void xConvCpuSparse(const float* const in, float* const out, const float rSigmaEff, const unsigned int rad, const unsigned int inWidth, const unsigned int outWidth, const unsigned int outHeight, const unsigned int inOutOffset, const unsigned int inOutDelta);

/**
 * \brief ...
 * \param in ...
 * \param out ...
 * \param rSigmaEff ...
 * \param rad ...
 * \param inHeight ...
 * \param outWidth ...
 * \param inOutOffset ...
 * \return void
 */
void yConvCpu(const float* const in, float* const out, const float rSigmaEff, const unsigned int rad, const unsigned int inHeight, const unsigned int outWidth, const unsigned int inOutOffset);

/**
 * \brief ...
 * \param in ...
 * \param out ...
 * \param rSigmaEff ...
 * \param rad ...
 * \param inHeight ...
 * \param outWidth ...
 * \param inOutOffset ...
 * \param inOutDelta ...
 * \return void
 */
void yConvCpuSparse(const float* const in, float* const out, const float rSigmaEff, const unsigned int rad, const unsigned int inHeight, const unsigned int outWidth, const unsigned int inOutOffset, const unsigned int inOutDelta);

#endif // CPU_CONVOLUTION_1D_H
