/**
 * \file
 * \brief EnergyStruct declaration
 */
#ifndef ENERGY_STRUCT_H
#define ENERGY_STRUCT_H

#include <vector>

/**
 * \brief ...
 */
struct EnergyStruct{
    int nEnergySamples = 0;             ///< ...
    int nEnergies = 0;                  ///< ...
    std::vector<float> energiesPerU;    ///< ...
    std::vector<float> peakDepths;      ///< ...
    std::vector<float> scaleFacts;      ///< ...
    std::vector<float> ciddMatrix;      ///< ...

    int nDensitySamples = 0;            ///< ...
    float densityScaleFact = 0;         ///< ...
    std::vector<float> densityVector;   ///< ...

    int nSpSamples = 0;                 ///< ...
    float spScaleFact = 0;              ///< ...
    std::vector<float> spVector;        ///< ...

    int nRRlSamples = 0;                ///< ...
    float rRlScaleFact = 0;             ///< ...
    std::vector<float> rRlVector;       ///< ...

#ifdef NUCLEAR_CORR
    std::vector<float> nucWeightMatrix; ///< ...
    std::vector<float> nucSqSigmaMatrix;///< ...
#endif // NUCLEAR_CORR

};

#endif // ENERGY_STRUCT_H
