/**
 * \file
 * \brief EnergyStruct declaration
 */
#ifndef ENERGY_STRUCT_H
#define ENERGY_STRUCT_H

#include <vector>

/**
 * \brief ...
 */
struct EnergyStruct{
    int nEnergySamples;                 ///< ...
    int nEnergies;                      ///< ...
    std::vector<float> energiesPerU;    ///< ...
    std::vector<float> peakDepths;      ///< ...
    std::vector<float> scaleFacts;      ///< ...
    std::vector<float> ciddMatrix;      ///< ...

    int nDensitySamples;                ///< ...
    float densityScaleFact;             ///< ...
    std::vector<float> densityVector;   ///< ...

    int nSpSamples;                     ///< ...
    float spScaleFact;                  ///< ...
    std::vector<float> spVector;        ///< ...

    int nRRlSamples;                    ///< ...
    float rRlScaleFact;                 ///< ...
    std::vector<float> rRlVector;       ///< ...

#ifdef NUCLEAR_CORR
    std::vector<float> nucWeightMatrix; ///< ...
    std::vector<float> nucSqSigmaMatrix;///< ...
#endif // NUCLEAR_CORR

};

#endif // ENERGY_STRUCT_H
