/**
 * \file
 * \brief GPU 2D Convolution function declarations
 */
#ifndef GPU_CONVOLUTION_2D_CUH
#define GPU_CONVOLUTION_2D_CUH

#include "vector_types.h"

/**
 * \brief ...
 * \param in ...
 * \param out ...
 * \param sigma ...
 * \param inWidth ...
 * \param outWidth ...
 * \param height ...
 * \param pixelSp ...
 * \param inOutOffset ...
 * \param inOutDelta ...
 * \return void
 */
__global__ void xConvGathResampGpu(float* const in, float* const out, float2* const sigma, const int inWidth, const int outWidth, const int height, const float pixelSp, const float inOutOffset, const float inOutDelta);

/**
 * \brief ...
 * \param in ...
 * \param out ...
 * \param sigma ...
 * \param width ...
 * \param inHeight ...
 * \param outHeight ...
 * \param pixelSp ...
 * \param inOutOffset ...
 * \param inOutDelta ...
 * \return void
 */
__global__ void yConvGathResampGpu(float* const in, float* const out, float2* const sigma, const int width, const int inHeight, const int outHeight, const float pixelSp, const float inOutOffset, const float inOutDelta);

/**
 * \brief ...
 * \param in ...
 * \param interm ...
 * \param out ...
 * \param sigmas ...
 * \param inDims ...
 * \param outDims ...
 * \param spotDelta ...
 * \param spotOffset ...
 * \param rayDelta ...
 * \param rayOffset ...
 * \param pxSpMult ...
 * \return void
 */
void gpuConvolution2D(float* const in, float* const interm, float* const out, float2* const sigmas, const uint3 inDims, const uint3 outDims, const float3 spotDelta, const float3 spotOffset, const float3 rayDelta, const float3 rayOffset, const float2 pxSpMult);

#endif // GPU_CONVOLUTION_2D_CUH
