/**
 * \file
 * \brief TracerParamStruct3 struct declaration
 */
#ifndef TRACER_PARAM_STRUCT3_H
#define TRACER_PARAM_STRUCT3_H

/**
 * \brief ...
 */
struct TracerParamStruct3{
    float3 step;            ///< ...
    float3 start;           ///< ...
    float3 gantryX;         ///< ...
    float3 gantryY;         ///< ...
    unsigned int steps;     ///< ...
    float worldStepLength;  ///< ...
};

#endif // TRACER_PARAM_STRUCT3_H
